name: building.net application

on:
    push:

jobs:
  build_dot_net:
    runs-on: ubuntu-latest

    steps:
    - name : setup dotnet sdk
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: checkout source
      uses: actions/checkout@v3

    - name: Git2Workshop
      run: ls -l
  
    - name: List the contents of the repository
      run: ls -R

    - name: list your repo before build
      run : ls -IR /bin

    - name: build app
      run: dotnet build

    - name: list files after build
      run: ls -IR /bin

        
        
        
